### ISSUE TITLE
Document infrastructure in newdot

### ISSUE THREAD

**Issue by spth** [freetdi/CFGs#2]
newdot seems to contain some infrastructure to do something.

It seems the default Makefile target converts all .dot graphs to .gr and requires ../convert_graph_type. "make all" creates some.out files that apparently are just long lists of filenames. There also is some bash script, that seems to expect some undocumented command-line parameters, and some python code.

The should be some documentation on what can be done, how, and what is required.

Maybe a README file and some comments in the Makefile? extractgraphs has such documentation (the extractgraphs documentation isn't perfect, but some documentation is usually better than none as long as it isn't totally wrong).

Philipp

**Comment by felix-salfelder** [comment]
done (more or less)
